package mcm.dsa.moneytrackingsystem;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author zazhe
 */
public class AddItemUI extends javax.swing.JFrame {

    /**
     * Creates new form AddItemUI
     */
    public AddItemUI() {
        initComponents();
        setVisible(true);

        dateField.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkBtn();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                checkBtn();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkBtn();
            }
        });

        valueField.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkBtn();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                checkBtn();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkBtn();
            }
        });

        addButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        categoryBox = new javax.swing.JComboBox<>();
        expenseButton = new javax.swing.JRadioButton();
        incomeButton = new javax.swing.JRadioButton();
        cancelButton = new javax.swing.JButton();
        dateField = new javax.swing.JFormattedTextField();
        valueField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Item");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Date (MM/DD/YYYY):");

        jLabel2.setText("Value:                          ₱");

        addButton.setText("OK");
        addButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        descriptionArea.setColumns(20);
        descriptionArea.setLineWrap(true);
        descriptionArea.setRows(5);
        jScrollPane1.setViewportView(descriptionArea);

        jLabel3.setText("Description:");

        categoryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grocery", "Transportation",
                "Self-Treat", "Property Tax", "Water Bill", "Electricity Bill" }));

        buttonGroup1.add(expenseButton);
        expenseButton.setSelected(true);
        expenseButton.setText("Expenses");
        expenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(incomeButton);
        incomeButton.setText("Income");
        incomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        dateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));
        dateField.setOpaque(true);

        valueField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(addButton, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(expenseButton)
                                        .addComponent(incomeButton))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dateField, GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addComponent(categoryBox, GroupLayout.Alignment.TRAILING,
                                                GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(valueField))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel3)
                                                        .addComponent(dateField, GroupLayout.PREFERRED_SIZE,
                                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(valueField, GroupLayout.PREFERRED_SIZE,
                                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addGap(25, 25, 25)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(expenseButton)
                                                        .addComponent(categoryBox, GroupLayout.PREFERRED_SIZE,
                                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(incomeButton)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(addButton, GroupLayout.PREFERRED_SIZE, 51,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, 51,
                                                GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)));

        categoryBox.setEnabled(expenseButton.isSelected());

        pack();
    }// </editor-fold>

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addButtonActionPerformed
        double valEx = Double.parseDouble(valueField.getText());
        String item[] = { dateField.getText(), valueExpense(), category(), descriptionArea.getText() };
        MoneyTrackerUI.list.add(item);

        switch (category()) {
            case "Grocery":
                MoneyTrackerUI.groceryTotal += valEx;
                break;
            case "Transportation":
                MoneyTrackerUI.transTotal += valEx;
                break;
            case "Self-Treat":
                MoneyTrackerUI.treatTotal += valEx;
                break;
            case "Property Tax":
                MoneyTrackerUI.taxTotal += valEx;
                break;
            case "Water Bill":
                MoneyTrackerUI.billWTotal += valEx;
                break;
            case "Electricity Bill":
                MoneyTrackerUI.billETotal += valEx;
                break;
            case "Income":
                MoneyTrackerUI.incomeTotal += valEx;
                break;
        }

        MoneyTrackerUI.setTotals();
        MoneyTrackerUI.display();

        dispose();
    }// GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }// GEN-LAST:event_cancelButtonActionPerformed

    private void expenseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_expenseButtonActionPerformed
        categoryBox.setEnabled(true);
    }// GEN-LAST:event_expenseButtonActionPerformed

    private void incomeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_incomeButtonActionPerformed
        categoryBox.setEnabled(false);
    }// GEN-LAST:event_incomeButtonActionPerformed

    private String valueExpense() {
        if (expenseButton.isSelected()) {
            return "-" + valueField.getText();
        }
        return valueField.getText();

    }

    private String category() {
        if (expenseButton.isSelected()) {
            return categoryBox.getSelectedItem().toString();
        }
        return "Income";
    }

    private void checkBtn() {
        boolean value1 = !dateField.getText().trim().isEmpty();
        boolean value2 = !valueField.getText().trim().isEmpty();
        addButton.setEnabled(value1 == true && value2 == true);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    public static javax.swing.JComboBox<String> categoryBox;
    private javax.swing.JFormattedTextField dateField;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JRadioButton expenseButton;
    private javax.swing.JRadioButton incomeButton;
    private javax.swing.JFormattedTextField valueField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}
