/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mcm.dsa.moneytrackingsystem;

import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author zazhe
 */
public class MoneyTrackerUI extends javax.swing.JFrame {

        /**
         * Creates new form MoneyTrackerUI
         */
        public MoneyTrackerUI() {
                initComponents();
        }

        public static ArrayList<String[]> list = new ArrayList<String[]>();
        public static double[] totals = new double[7];
        public static double groceryTotal = 0;
        public static double transTotal = 0;
        public static double treatTotal = 0;
        public static double taxTotal = 0;
        public static double billWTotal = 0;
        public static double billETotal = 0;
        public static double incomeTotal = 0;

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="GeneratedA
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jButton_Add = new javax.swing.JButton();
                jButton_Delete = new javax.swing.JButton();
                jButton_Summary = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Money Tracking System");
                setBackground(new java.awt.Color(153, 153, 153));
                setResizable(false);

                jPanel1.setBackground(new java.awt.Color(102, 102, 102));

                jLabel1.setBackground(new java.awt.Color(255, 255, 255));
                jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("MONEY TRACKING SYSTEM");
                jLabel1.setOpaque(true);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                713, Short.MAX_VALUE)
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                46,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jPanel2.setBackground(new java.awt.Color(102, 102, 102));

                jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

                jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new String[] {
                                                "Date", "Expense", "Category", "Description"
                                },
                                0) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jTable1.setToolTipText("");
                jTable1.setCellSelectionEnabled(true);
                jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                jTable1.setGridColor(new java.awt.Color(102, 102, 102));
                jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jTable1.setShowGrid(false);
                jScrollPane2.setViewportView(jTable1);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel2Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jScrollPane2)
                                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                260, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jButton_Add.setBackground(new java.awt.Color(204, 204, 204));
                jButton_Add.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
                jButton_Add.setText("Add New Expense");
                jButton_Add.setBorder(
                                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jButton_Add.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_AddActionPerformed(evt);
                        }
                });

                jButton_Delete.setBackground(new java.awt.Color(204, 204, 204));
                jButton_Delete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
                jButton_Delete.setText("Delete");
                jButton_Delete.setToolTipText("Delete selected row");
                jButton_Delete.setEnabled(false);
                jButton_Delete.setBorder(
                                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_DeleteActionPerformed(evt);
                        }
                });

                jButton_Summary.setBackground(new java.awt.Color(204, 204, 204));
                jButton_Summary.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
                jButton_Summary.setText("Show Summary");
                jButton_Summary.setToolTipText("Delete selected row");
                jButton_Summary.setEnabled(false);
                jButton_Summary.setBorder(
                                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jButton_Summary.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_SummaryActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jPanel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(75, 75, 75)
                                                                .addComponent(jButton_Add,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                190,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                33, Short.MAX_VALUE)
                                                                .addComponent(jButton_Delete,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                190,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(32, 32, 32)
                                                                .addComponent(jButton_Summary,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                190,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(75, 75, 75)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton_Add,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                80,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jButton_Delete,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                80,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jButton_Summary,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                80,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap()));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_AddActionPerformed
                new AddItemUI();
        }// GEN-LAST:event_jButton_AddActionPerformed

        private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_DeleteActionPerformed
                int selectedIndex = jTable1.getSelectedRow();
                if (selectedIndex == -1) {
                    String removed = list.get(list.size() - 1)[2];
                    double val = Double.parseDouble(list.get(list.size() - 1)[1]);
                    
                    switch (removed) {
                        case "Grocery":
                            groceryTotal += val;
                            break;
                        case "Transportation":
                            transTotal += val;
                            break;
                        case "Self-Treat":
                            treatTotal += val;
                            break;
                        case "Property Tax":
                            taxTotal += val;
                            break;
                        case "Water Bill":
                            billWTotal += val;
                            break;
                        case "Electricity Bill":
                            billETotal += val;
                            break;
                        case "Income":
                            incomeTotal -= val;
                            break;
                    }
                    list.remove(list.size() - 1);
                } else {
                    String removed = list.get(selectedIndex)[2];
                    double val = Double.parseDouble(list.get(selectedIndex)[1]);
                    
                    switch (removed) {
                        case "Grocery":
                            MoneyTrackerUI.groceryTotal += val;
                            break;
                        case "Transportation":
                            MoneyTrackerUI.transTotal += val;
                            break;
                        case "Self-Treat":
                            MoneyTrackerUI.treatTotal += val;
                            break;
                        case "Property Tax":
                            MoneyTrackerUI.taxTotal += val;
                            break;
                        case "Water Bill":
                            MoneyTrackerUI.billWTotal += val;
                            break;
                        case "Electricity Bill":
                            MoneyTrackerUI.billETotal += val;
                            break;
                        case "Income":
                            MoneyTrackerUI.incomeTotal -= val;
                            break;
                    }
                    list.remove(selectedIndex);
                }
                setTotals();
                display();
        }// GEN-LAST:event_jButton_DeleteActionPerformed

        private void jButton_SummaryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_SummaryActionPerformed
                SummaryUI CC = new SummaryUI("Summary", "Expense Totals");
                CC.pack();
                CC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }// GEN-LAST:event_jButton_SummaryActionPerformed

        public static void sortList() {
                for (int i = 0; i < list.size(); i++) {
                        for (int j = i + 1; j < list.size(); j++) {
                                if (list.get(i)[0].compareTo(list.get(j)[0]) > 0) {
                                        String temp[] = list.get(i);
                                        list.set(i, list.get(j));
                                        list.set(j, temp);
                                }
                        }
                }
        }
        
        public static void setTotals() {
            double[] arr = {groceryTotal, transTotal, treatTotal, taxTotal, billWTotal, billETotal, incomeTotal};
            for (int i = 0; i < totals.length; i++) {
                totals[i] = arr[i];
            }
        }

        public static void display() {
                double sum = 0;
                if (!list.isEmpty()) {
                        jButton_Delete.setEnabled(true);
                        jButton_Summary.setEnabled(true);
                } else {
                        jButton_Delete.setEnabled(false);
                        jButton_Summary.setEnabled(false);
                }

                sortList();

                String[] col = { "Date", "Expense", "Category", "Description" };
                DefaultTableModel model = new DefaultTableModel(col, 0);
                Object[] data = new Object[4];

                for (int i = 0; i < list.size(); i++) {
                        for (int j = 0; j < list.get(i).length; j++) {
                                data[j] = list.get(i)[j];
                        }
                        model.addRow(data);
                }

                jTable1 = new JTable(model);
                jScrollPane2.setViewportView(jTable1);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MoneyTrackerUI.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MoneyTrackerUI.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MoneyTrackerUI.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MoneyTrackerUI.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MoneyTrackerUI().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton_Add;
        private static javax.swing.JButton jButton_Delete;
        private static javax.swing.JButton jButton_Summary;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private static javax.swing.JScrollPane jScrollPane2;
        private static javax.swing.JTable jTable1;
        // End of variables declaration//GEN-END:variables
}
